\ProvidesClass{wettbewerbszettel}
\LoadClass{uebungszettel} 
\usepackage[a6paper]{geometry}


%Kopf- und Fuﬂzeile---------------------------
\pagestyle{scrheadings}
\clearscrheadings
\clearscrplain
\lohead{\includegraphics[height=15px]{fslogo}}
\rohead{\includegraphics[height=15px]{aware_sw}}
\lofoot{\small C-Programmierkurs von Jesko \& Lars}
\cofoot{}
\rofoot{\tiny SS10}
\cohead{\small Wettbewerb}
\setheadsepline{.5pt} % Linie unter dem Head
\setfootsepline{.2pt} % Ganzunten
%---------------------------------------------

